name = "github-linked-role"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 0 * * *"]

# パブリックな設定値のみ記載OK
[vars]
TARGET_GUILD_ID = "1483797999519010957"
TARGET_CHANNEL_ID = "1483798584502779974"
GITHUB_CLIENT_ID = "Ov23lih47fNb6rXghUyj"
DISCORD_CLIENT_ID = "1545721397278408725"

[[d1_databases]]
binding = "DB"
database_name = "test"
database_id = "bc9a890f-db0e-4078-acff-b095447d66d8" # D1のIDは公開されても安全